<?php

namespace Elfec\SgauthBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * perfilesAplicacionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class perfilesAplicacionesRepository extends BaseRepository
{
    /**
     * @param $data
     * @param $login
     * @return \Elfec\SgauthBundle\Model\RespuestaSP
     */
    public function grabarPerfilApp($data, $login)
    {
        $result = new \Elfec\SgauthBundle\Model\RespuestaSP();
        try {
            $conection = $this->_em->getConnection();
            $st = $conection->prepare("SELECT elfec.grabar_perfil_app (
            :p_id_perfil::numeric,
            :p_id_aplic::numeric,
            :p_login_usr::VARCHAR);");
            $st->bindValue("p_id_perfil", $this->getValueArray($data, "id_perfil", null));
            $st->bindValue("p_id_aplic", $this->getValueArray($data, "id_aplic", null));
            $st->bindValue(":p_login_usr", $login);
            $st->execute();
            $response = $st->fetchAll();
            $result = $this->respuestaSP($response);
        } catch (\Exception $e) {
            $result->success = false;
            $result->msg = $e->getMessage();
        }
        return $result;

    }
}
