<?php

namespace Elfec\SgauthBundle\Entity\Repository;


/**
 * usuariosAreasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class usuariosAreasRepository extends BaseRepository
{
}
