elfec_sgauth:
    resource: "@ElfecSgauthBundle/Resources/config/routing.yml"
    prefix:   /backend

front-end:
    pattern:  /
    defaults: { _controller: ElfecSgauthBundle:Default:index }

front-end-logon:
    pattern : /logon
    defaults: { _controller: ElfecSgauthBundle:Default:logon }

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc/api

token:
    type:     rest
    prefix:   /login
    resource: Elfec\SgauthBundle\Controller\TokenController