elfec_sgauth:
    resource: "@ElfecSgauthBundle/Resources/config/routing.yml"
    prefix:   /backend

front-end:
    resource: Elfec\SgauthBundle\Controller\DefaultController
    type:     annotation
    prefix:   /

elfec-config:
    resource: Elfec\SgauthBundle\Controller\ItemsController
    type:     rest
    prefix:   /api

elfec-rest-api:
    resource: Elfec\SgauthBundle\Controller\FreeServicesController
    type:     rest
    prefix:   /rest-api
#    defaults: { _controller: ElfecSgauthBundle:Default:index }

#front-end-logon:
#    pattern : /logon
#    defaults: { _controller: ElfecSgauthBundle:Default:logon }
#
#front-end-recuperacion:
#    pattern : /recuperacion
#    defaults: { _controller: ElfecSgauthBundle:Default:recuperacion }
#


NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc/api

token:
    type:     rest
    prefix:   /login
    resource: Elfec\SgauthBundle\Controller\TokenController

elfec_erp:
    resource: "@ElfecErpBundle/Resources/config/routing.yml"
    prefix:   /erp