security:
    encoders:
            Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
            ROLE_ADMIN: ROLE_USER

    providers:
            in_memory:
                memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        wsse_secured:
              pattern:   ^/backend/.*
              stateless:    true
              jwt: true
              anonymous : true
        wsse_report:
              pattern:   ^/reportes/.*
              stateless:    true
              jwt: true
              anonymous : true
        main:
            anonymous: ~
    access_control:
            - { path: ^/logon, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/backend, roles: IS_AUTHENTICATED_ANONYMOUSLY }

