<?php

namespace Elfec\ErpBundle\Repository;
use Elfec\SgauthBundle\Entity\Repository\BaseRepository;

/**
 * EmpleadosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpleadosRepository extends BaseRepository
{
}
