<?php

namespace Elfec\ErpBundle\Repository;
use Elfec\SgauthBundle\Entity\Repository\BaseRepository;

/**
 * ProveedoresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProveedoresRepository extends BaseRepository
{
}
