services:
    jwt.security.authentication.provider:
        class: Elfec\SgauthBundle\Security\Authentication\Provider\JWTProvider
        arguments: ["", "%kernel.cache_dir%/security/nonces"]

    jwt.security.authentication.listener:
        class: Elfec\SgauthBundle\Security\Firewall\JWTListener
        arguments: ["@security.token_storage", "@security.authentication.manager"]
        calls:
            - [ setContainer,[@service_container] ]
#    servicios para usuarios
    sgauthbundle.usuarios_service:
        class: Elfec\SgauthBundle\Services\UsuariosService
        arguments: ["@doctrine.orm.entity_manager"]

#    servicios para usuarios
    sgauthbundle.perfiles_service:
        class: Elfec\SgauthBundle\Services\PerfilesService
        arguments: ["@doctrine.orm.entity_manager"]

#    servicios para usuarios
    sgauthbundle.aplicaciones_service:
        class: Elfec\SgauthBundle\Services\AplicacionesService
        arguments: ["@doctrine.orm.entity_manager"]

#    servicios para usuarios
    sgauthbundle.MenuOpciones_service:
        class: Elfec\SgauthBundle\Services\MenuOpcionesService
        arguments: ["@doctrine.orm.entity_manager"]

#    servicios para autenticacion
    sgauthbundle.autenticacion_service:
        class: Elfec\SgauthBundle\Services\AutenticacionService
        arguments: ["@doctrine.orm.sgauth_entity_manager"]

#   servicio para historicos
    sgauthbundle.historicos_service:
            class: Elfec\SgauthBundle\Services\HistoricosService
            arguments: ["@doctrine.orm.entity_manager"]

#   servicio para envio de correo
    sgauthbundle.correo_service:
            class: Elfec\SgauthBundle\Services\CorreoService
            arguments: ["@mailer","@templating"]

#   servicio para la recuperacion de contraseña
    sgauthbundle.recuperacion_service:
            class: Elfec\SgauthBundle\Services\RecuperacionService
            arguments: ["@doctrine.orm.sgauth_entity_manager" , "@nzo_url_encryptor" , "@sgauthbundle.correo_service"]
